# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.10

# Mod Properties
mod_version=3.0.3
maven_group=me.tolek
archives_base_name=modforlazypeople
file_version=1.0.1

# Dependencies
fabric_version=0.118.0+1.21.4
libgui_version=12.0.1+1.21.2
mod_menu_version=12.0.0
gson_version=2.9.0
jupiter_version=5.8.1
javax_websocket_version=1.1
tyrus_version=1.17